def countdown():
    i=5
    while i>0:
        yield i
        i-=1
for i in countdown():
    print(i)
#ROUND 1
#1:CALL THE FUNCTION COUNTDOWN
#2:STOP/PAUSE THE EXECUTION WHERE YIELD ENCOUNTERS
#3:RETURNS THE VALUE I=5

#ROUND 2
#1:CALL THE FUNCTION WILL BEGINS THE EXECUTION WHERE LEFT OFF i-=1
#2:STOP/PAUSE THE EXECUTION WHERE YIELD ENCOUNTERS
#3:RETURN i=4

#ROUND 3
#1:CALL THE FUNCTION i-=1
#2:STOP/PAUSE THE EXECUTION WHERE YIELD ENCOUNTERS
#3:RETURN i=3

#ROUND 4
#1:CALL THE FUNCTION i-=1
#2:STOP/PAUSE THE EXECUTION WHERE YIELD ENCOUNTERS
#3:RETURN i=2

#ROUND 5
#1:CALL THE FUNCTION i-=1
#2:STOP/PAUSE THE EXECUTION WHERE YIELD ENCOUNTERS
#3:RETURN i=1
